name: Create New Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Enter the name of the new repository'
        required: true

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create New Repo
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.APIACCESS }}
        with:
          script: |
            const github = context.github;
            const orgName = 'im-sandbox-koteshwarraomyneni';
            const repoName = '${{ github.event.inputs.repo_name }}';
            const repoData = {name: repoName, auto_init: true};
            const newRepo = await github.repos.createInOrg({org: orgName, ...repoData});
            console.log(`Created new repo: ${newRepo.data.html_url}`);

