name: Create Project, Repository, and Workflow
on:
  push:
    branches: [ main ]

 
env:
  ORG_NAME: im-sandbox-koteshwarraomyneni
  PROJECT_NAME: project1
  REPO_NAME: newrepofromworlflow
  BRANCH_NAME: main
  WORKFLOW_NAME: My Workflow
  WORKFLOW_FILE: my-workflow.yml


jobs:
  
  create-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      run: |
        hub create -d "A new repository" -p ${PROJECT_NAME} ${REPO_NAME}
  add-workflow:
    needs: create-repo
    runs-on: ubuntu-latest
    steps:
    - name: Add Workflow
      run: |
        curl -X PUT \
             -H "Authorization: token ${{ secrets.API_ACCESS1 }}" \
             -H "Accept: application/vnd.github.inertia-preview+json" \
             -d '{"name":"'"${WORKFLOW_NAME}"'", "path":"'"${WORKFLOW_FILE}"'", "branch":"'"${BRANCH_NAME}"'"}' \
             https://api.github.com/repos/${REPO_NAME}/contents/${WORKFLOW_FILE}