name: Create New Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Enter the name of the new repository'
        required: true

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create New Repo
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.APIACCESS1 }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/im-sandbox-koteshwarraomyneni/repos \
            -d '{"name": "'"${{ github.event.inputs.repo_name }}"'"}'

  create_project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.APIACCESS1 }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Project
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh project create --name "new-project" --body "New project created from workflow" --private
