name: Create Repository
on:
  push:
    branches:
      - main
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install @actions/github
      - name: Create repository
        uses: actions/github-script@v5
        with:
          script: |
            const { GitHub, context } = require('@actions/github');
            const octokit = new GitHub(process.env.GITHUB_TOKEN);
            const { owner } = context.repo;
            const repoName = 'my-repo';
            const repoDescription = 'My repository description';
            const repository = await octokit.repos.createForAuthenticatedUser({
