name: Create Project, Repository, and Workflow
on:
  push:
    branches: [ main ]
jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
    - name: Create Project
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.inertia-preview+json" \
             -d '{"name":"My Project", "body": "A new project"}' \
             https://api.github.com/orgs/myorg/projects
  create-repo:
    needs: create-project
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      run: |
        hub create -d "A new repository" -p "My Project" myrepo