name: Create Project

on:
  repository:
    types: [created]

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Create Project
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.projects.createForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "New Project",
            });
            const projectId = response.data.id;
            await octokit.projects.createColumn({
              project_id: projectId,
              name: "To do",
            });
            await octokit.projects.createColumn({
              project_id: projectId,
              name: "In progress",
            });
            await octokit.projects.createColumn({
              project_id: projectId,
              name: "Done",
            });
