name: Create New Repository and Project

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Enter the name of the new repository'
        required: true
      project_name:
        description: 'Enter the name of the new project'
        required: true

jobs:
  create_repo_and_project:
    runs-on: ubuntu-latest

    steps:
      - name: Create New Repo
        run: |
          gh repo create im-sandbox-koteshwarraomyneni/${{ github.event.inputs.repo_name }} --private
          echo "::set-output name=repo_name::${{ github.event.inputs.repo_name }}"

      - name: Create New Project
        run: |
          gh project create --name "${{ github.event.inputs.project_name }}" --private
          echo "::set-output name=project_url::$(gh project view | grep "View on GitHub" | awk '{print $4}')"

      - name: Add Repository to Project
        run: |
          gh api "/repos/im-sandbox-koteshwarraomyneni/${{ steps.create_new_repo.outputs.repo_name }}/projects" -H "Accept: application/vnd.github.inertia-preview+json" -X POST -d '{"name": "${{ github.event.inputs.project_name }}"}'

      - name: Create List of Tickets
        run: |
          gh issue create --title "Ticket 1" --body "This is the body of Ticket 1" --assignee @username
          gh issue create --title "Ticket 2" --body "This is the body of Ticket 2" --assignee @username
          gh issue create --title "Ticket 3" --body "This is the body of Ticket 3" --assignee @username
