name: Create New Angular App

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Enter the name of the new repository'
        required: true
      app_name:
        description: 'Enter the name of the new Angular application'
        required: true

jobs:
  create_repo_and_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Create New Repo
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.APIACCESS1 }}
        with:
          script: |
            const github = context.github;
            const orgName = 'your-organization-name';
            const repoName = '${{ github.event.inputs.repo_name }}';
            const repoData = {name: repoName};
            const newRepo = await github.repos.createInOrg({org: orgName, ...repoData});
            console.log(`Created new repo: ${newRepo.data.html_url}`);

      - name: Create Angular App
        run: |
          ng new ${{ github.event.inputs.app_name }}

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Initial commit"
          git push origin main

      - name: Label Incubator Code
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.APIACCESS1 }}
        with:
          script: |
            const github = context.github;
            const orgName = 'your-organization-name';
            const repoName = '${{ github.event.inputs.repo_name }}';
            const labelName = 'incubator';
            const labelColor = 'F2D04B';
            const labelData = {name: labelName, color: labelColor};
            const newLabel = await github.issues.createLabel({owner: orgName, repo: repoName, ...labelData});
            console.log(`Created new label: ${newLabel.data.name}`);
